version: '3.7'

services:
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    ports:
      - 3001:80
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - 3000:3000
