import { Button } from '@packages/ui-kit';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Client Next app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Client app</h1>
        <Button>Button from UI Kit package</Button>
      </main>
    </>
  );
}
